name: Deploy Jekyll with GitHub Pages dependencies preinstalled
on:
  pull_request:
    paths-ignore:
      - "docs/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'